### ISSUE TITLE
should show local peers on discovery page

### ISSUE THREAD

**Issue by mmckegg** [mmckegg/ferment#44]
As @PrasannaVenkadesh brought up in #26, local peers are not showing on the discovery page. I think this potentially could be one of the best features of ferment, local network based discovery! **Support for this should be added!**

Also would be nice to prioritise local peers in the "Who to follow" section in sidebar.

**Comment by PrasannaVenkadesh** [comment]
Yes, local peers discovery is very useful for wireless community networks which aims to create a decentralized infrastructure of it's own instead of relying on ISP or other central agencies without the need to run a server anywhere.

[Patchwork](https://ssbc.github.io/patchwork) which already is built using SSB does this, I think ferment already does local peer discovery and connects to them in background. We just need some simple logic to display them on discovery page.

**Comment by PrasannaVenkadesh** [comment]
@mmckegg I saw the webtorrent tracker url `ws://pub.ferment.audio:43770` has been hard coded into the application (file: `ssb-config.js`). Which means pub.ferment.audio lives on the Internet and is it possible for peers on a LAN or WLAN without Internet seed the audio files with the current development?

**Comment by mmckegg** [comment]
@PrasannaVenkadesh Yes, this is far from ideal. However it does seem still work locally (with no internet) via DHT. The trackers are there to help find peers via the internet.

In the future, all ferment pubs will be trackers. At the moment though, there is only **one** ferment pub, and that's my one.

**Comment by PrasannaVenkadesh** [comment]
@mmckegg +1 for DHT.

**Comment by mmckegg** [comment]
2952cc9bee0c20775630259d866a45b4b839c8f9 makes local users appear in discovery feed. Closing!

**Comment by PrasannaVenkadesh** [comment]
@mmckegg Local peer discovery is flawless.

But this doesn't work as expected https://github.com/mmckegg/ferment/issues/44#issuecomment-257488863 The other machine on the network says `0% Finding peers`

![bug_ferment](https://cloud.githubusercontent.com/assets/788244/20008843/295f042a-a2c8-11e6-845b-c05942bedc12.png)

And here is the log in my terminal

![bug_ferment_log](https://cloud.githubusercontent.com/assets/788244/20008886/4f1cc74c-a2c8-11e6-9266-68dffd2e79d0.png)
